FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY tests/integration-be ./tests/integration-be

CMD ["npm", "--prefix", "tests/integration-be", "run", "test"]
