FROM node:22-alpine

WORKDIR /app
RUN chown node:node /app

COPY --chown=node:node package*.json ./

USER node

RUN npm install

COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node tests/integration-be ./tests/integration-be

CMD ["npm", "--prefix", "tests/integration-be", "run", "test"]
