FROM node:22-alpine

WORKDIR /app
RUN chown node:node /app

COPY --chown=node:node package*.json ./

USER node

RUN npm ci

COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node src ./src
COPY --chown=node:node public ./public

EXPOSE 3000

CMD ["npm", "run", "dev:api"]
