FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY client/package*.json ./client/

RUN npm ci
RUN cd client && npm ci

COPY . .

RUN npm run build:ts
RUN cd client && npm run build
