FROM node:22-alpine

WORKDIR /app/backend
RUN chown -R node:node /app

COPY --chown=node:node backend/package*.json ./
COPY --chown=node:node .npmrc* ./
COPY --chown=node:node backend/prisma ./prisma

USER node

RUN npm ci
RUN rm -f .npmrc

COPY --chown=node:node backend/ ./

EXPOSE 3000

CMD ["npm", "run", "dev:api"]
