FROM node:22-alpine

WORKDIR /app
RUN chown node:node /app

COPY --chown=node:node package*.json .npmrc* ./
COPY --chown=node:node prisma ./prisma

USER node

RUN npm ci && rm -f .npmrc
COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node tests/integration-be ./tests/integration-be

CMD ["npm", "--prefix", "tests/integration-be", "run", "test"]
