/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{*}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
    };
    "/characters/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate a new random character */
        post: {
            parameters: {
                query?: {
                    locale?: PathsCharactersNewPostParametersQueryLocale;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        class_id?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                current_tier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersNewPostResponses201ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computed_modifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersNewPostResponses201ContentApplicationJsonComputed_modifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersNewPostResponses201ContentApplicationJsonComputed_modifiersOrigin;
                                origin_key?: string;
                                origin_name?: string;
                            }[];
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a character by ID */
        get: {
            parameters: {
                query?: {
                    locale?: PathsCharactersIdGetParametersQueryLocale;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                current_tier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdGetResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computed_modifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdGetResponses200ContentApplicationJsonComputed_modifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersIdGetResponses200ContentApplicationJsonComputed_modifiersOrigin;
                                origin_key?: string;
                                origin_name?: string;
                            }[];
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a character */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Character deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update a character */
        patch: {
            parameters: {
                query?: {
                    locale?: PathsCharactersIdPatchParametersQueryLocale;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        current_hp?: number;
                        max_hp?: number;
                        omens?: number;
                        max_omens?: number;
                        silver?: number;
                        strength?: number;
                        agility?: number;
                        presence?: number;
                        toughness?: number;
                        trait1?: string;
                        trait2?: string;
                        habit?: string;
                        tale?: string;
                        body_description?: string;
                        origin?: string;
                        notes?: string;
                        abilities?: {
                            key?: string;
                            name?: string;
                            description?: string;
                        }[];
                        equipment?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            uses?: boolean[];
                            dice?: number[];
                            tags?: string[];
                            max_tier?: number;
                            current_tier?: number;
                        }[];
                        storage?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            uses?: boolean[];
                            dice?: number[];
                            tags?: string[];
                            max_tier?: number;
                            current_tier?: number;
                        }[];
                        equipped_weapons?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            tags?: string[];
                        }[];
                        equipped_armor?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            max_tier?: number;
                            current_tier?: number;
                            tags?: string[];
                        } | null;
                        modifiers?: {
                            id?: string;
                            name?: string;
                            value?: number;
                            source?: string;
                            /** @enum {string} */
                            statistic?: PathsCharactersIdPatchRequestBodyApplicationJsonModifiersStatistic;
                            exclude?: string[];
                            comment?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                current_tier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdPatchResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computed_modifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdPatchResponses200ContentApplicationJsonComputed_modifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersIdPatchResponses200ContentApplicationJsonComputed_modifiersOrigin;
                                origin_key?: string;
                                origin_name?: string;
                            }[];
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/characters/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Claim a guest character for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List characters for current session/user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                max_tier?: number;
                                current_tier?: number;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                current_tier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersGetResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computed_modifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersGetResponses200ContentApplicationJsonComputed_modifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersGetResponses200ContentApplicationJsonComputed_modifiersOrigin;
                                origin_key?: string;
                                origin_name?: string;
                            }[];
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        }[];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search items with fuzzy matching and locale awareness */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    locale?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            item_type?: string;
                            id?: number;
                            key?: string;
                            name?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment/{itemType}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch full item by type and id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemType: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsCharactersNewPostParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsCharactersNewPostResponses201ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersNewPostResponses201ContentApplicationJsonComputed_modifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersNewPostResponses201ContentApplicationJsonComputed_modifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet"
}
export enum PathsCharactersIdGetParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsCharactersIdGetResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdGetResponses200ContentApplicationJsonComputed_modifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdGetResponses200ContentApplicationJsonComputed_modifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet"
}
export enum PathsCharactersIdPatchParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsCharactersIdPatchRequestBodyApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdPatchResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdPatchResponses200ContentApplicationJsonComputed_modifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdPatchResponses200ContentApplicationJsonComputed_modifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet"
}
export enum PathsCharactersGetResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersGetResponses200ContentApplicationJsonComputed_modifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersGetResponses200ContentApplicationJsonComputed_modifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet"
}
export type operations = Record<string, never>;
