/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate a new random character */
        post: {
            parameters: {
                query?: {
                    /** @description Locale (en, pl) */
                    locale?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        class_id?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            abilities?: {
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                tags?: string[];
                            } | null;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a character by ID */
        get: {
            parameters: {
                query?: {
                    /** @description Locale (en, pl) */
                    locale?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            abilities?: {
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                tags?: string[];
                            } | null;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a character */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Character deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update a character */
        patch: {
            parameters: {
                query?: {
                    /** @description Locale (en, pl) */
                    locale?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        current_hp?: number;
                        omens?: number;
                        silver?: number;
                        equipment?: {
                            key?: string;
                            name?: string;
                            description?: string;
                        }[];
                        equipped_weapons?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            tags?: string[];
                        }[];
                        equipped_armor?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            max_tier?: number;
                            tags?: string[];
                        } | null;
                        abilities?: {
                            name?: string;
                            description?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            class_id?: number;
                            class_name?: string;
                            class_description?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            max_hp?: number;
                            current_hp?: number;
                            omens?: number;
                            max_omens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            body_description?: string;
                            trait1?: string;
                            trait2?: string;
                            abilities?: {
                                name?: string;
                                description?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                            }[];
                            equipped_weapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                            }[];
                            equipped_armor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                max_tier?: number;
                                tags?: string[];
                            } | null;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
