/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{*}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    "*": string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
    };
    "/characters/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate a new random character */
        post: {
            parameters: {
                query?: {
                    locale?: PathsCharactersNewPostParametersQueryLocale;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        classId?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersNewPostResponses201ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersNewPostResponses201ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersNewPostResponses201ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get total number of characters in the database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a character by ID */
        get: {
            parameters: {
                query?: {
                    locale?: PathsCharactersIdGetParametersQueryLocale;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdGetResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdGetResponses200ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersIdGetResponses200ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a character */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Character deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update a character */
        patch: {
            parameters: {
                query?: {
                    locale?: PathsCharactersIdPatchParametersQueryLocale;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        currentHp?: number;
                        maxHp?: number;
                        omens?: number;
                        maxOmens?: number;
                        silver?: number;
                        strength?: number;
                        agility?: number;
                        presence?: number;
                        toughness?: number;
                        trait1?: string;
                        trait2?: string;
                        habit?: string;
                        tale?: string;
                        bodyDescription?: string;
                        origin?: string;
                        notes?: string;
                        abilities?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            comment?: string;
                        }[];
                        equipment?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            uses?: boolean[];
                            dice?: number[];
                            tags?: string[];
                            maxTier?: number;
                            currentTier?: number;
                            amount?: number;
                            ammoType?: string;
                        }[];
                        storage?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            uses?: boolean[];
                            dice?: number[];
                            tags?: string[];
                            maxTier?: number;
                            currentTier?: number;
                            amount?: number;
                            ammoType?: string;
                        }[];
                        equippedWeapons?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            tags?: string[];
                            ammoType?: string;
                        }[];
                        equippedArmor?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            maxTier?: number;
                            currentTier?: number;
                            tags?: string[];
                        } | null;
                        modifiers?: {
                            id?: string;
                            name?: string;
                            value?: number;
                            source?: string;
                            /** @enum {string} */
                            statistic?: PathsCharactersIdPatchRequestBodyApplicationJsonModifiersStatistic;
                            exclude?: string[];
                            comment?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdPatchResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/characters/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Claim a guest character for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List characters for current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersGetResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsCharactersGetResponses200ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsCharactersGetResponses200ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        }[];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search items with fuzzy matching and locale awareness */
        get: {
            parameters: {
                query: {
                    q: string;
                    locale?: PathsEquipmentSearchGetParametersQueryLocale;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            itemType?: string;
                            id?: number;
                            key?: string;
                            name?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment/{itemType}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch full item by type and id */
        get: {
            parameters: {
                query?: {
                    key?: string;
                };
                header?: never;
                path: {
                    itemType: PathsEquipmentItemTypeIdGetParametersPathItemType;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsCharactersNewPostParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsCharactersNewPostResponses201ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersNewPostResponses201ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersNewPostResponses201ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsCharactersIdGetParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsCharactersIdGetResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdGetResponses200ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdGetResponses200ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsCharactersIdPatchParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsCharactersIdPatchRequestBodyApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdPatchResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsCharactersGetResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersGetResponses200ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsCharactersGetResponses200ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsEquipmentSearchGetParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsEquipmentItemTypeIdGetParametersPathItemType {
    weapon = "weapon",
    armor = "armor",
    equipment = "equipment",
    pet = "pet"
}
export type operations = Record<string, never>;
