/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate a new random character */
        post: {
            parameters: {
                query?: {
                    locale?: PathsApiCharactersNewPostParametersQueryLocale;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        classId?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersNewPostResponses201ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersNewPostResponses201ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsApiCharactersNewPostResponses201ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get total number of characters in the database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a character by ID */
        get: {
            parameters: {
                query?: {
                    locale?: PathsApiCharactersIdGetParametersQueryLocale;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersIdGetResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersIdGetResponses200ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsApiCharactersIdGetResponses200ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a character */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Character deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update a character */
        patch: {
            parameters: {
                query?: {
                    locale?: PathsApiCharactersIdPatchParametersQueryLocale;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        currentHp?: number;
                        maxHp?: number;
                        omens?: number;
                        maxOmens?: number;
                        silver?: number;
                        strength?: number;
                        agility?: number;
                        presence?: number;
                        toughness?: number;
                        trait1?: string;
                        trait2?: string;
                        habit?: string;
                        tale?: string;
                        bodyDescription?: string;
                        origin?: string;
                        notes?: string;
                        abilities?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            comment?: string;
                        }[];
                        equipment?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            uses?: boolean[];
                            dice?: number[];
                            tags?: string[];
                            maxTier?: number;
                            currentTier?: number;
                            amount?: number;
                            ammoType?: string;
                        }[];
                        storage?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            uses?: boolean[];
                            dice?: number[];
                            tags?: string[];
                            maxTier?: number;
                            currentTier?: number;
                            amount?: number;
                            ammoType?: string;
                        }[];
                        equippedWeapons?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            tags?: string[];
                            ammoType?: string;
                        }[];
                        equippedArmor?: {
                            key?: string;
                            name?: string;
                            description?: string;
                            dice?: number[];
                            maxTier?: number;
                            currentTier?: number;
                            tags?: string[];
                        } | null;
                        modifiers?: {
                            id?: string;
                            name?: string;
                            value?: number;
                            source?: string;
                            /** @enum {string} */
                            statistic?: PathsApiCharactersIdPatchRequestBodyApplicationJsonModifiersStatistic;
                            exclude?: string[];
                            comment?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersIdPatchResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsApiCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: {
                locale?: PathsApiCharactersGetParametersQueryLocale;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List characters for current user */
        get: {
            parameters: {
                query?: {
                    locale?: PathsApiCharactersGetParametersQueryLocale;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            classId?: number;
                            className?: string;
                            classDescription?: string;
                            origin?: string;
                            strength?: number;
                            agility?: number;
                            presence?: number;
                            toughness?: number;
                            maxHp?: number;
                            currentHp?: number;
                            omens?: number;
                            maxOmens?: number;
                            silver?: number;
                            habit?: string;
                            tale?: string;
                            bodyDescription?: string;
                            trait1?: string;
                            trait2?: string;
                            notes?: string;
                            abilities?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                comment?: string;
                            }[];
                            equipment?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            storage?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                uses?: boolean[];
                                dice?: number[];
                                tags?: string[];
                                maxTier?: number;
                                currentTier?: number;
                                amount?: number;
                                ammoType?: string;
                            }[];
                            equippedWeapons?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                tags?: string[];
                                ammoType?: string;
                            }[];
                            equippedArmor?: {
                                key?: string;
                                name?: string;
                                description?: string;
                                dice?: number[];
                                maxTier?: number;
                                currentTier?: number;
                                tags?: string[];
                            } | null;
                            modifiers?: {
                                id?: string;
                                name?: string;
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersGetResponses200ContentApplicationJsonModifiersStatistic;
                                exclude?: string[];
                                comment?: string;
                            }[];
                            computedModifiers?: {
                                value?: number;
                                source?: string;
                                /** @enum {string} */
                                statistic?: PathsApiCharactersGetResponses200ContentApplicationJsonComputedModifiersStatistic;
                                exclude?: string[];
                                /** @enum {string} */
                                origin?: PathsApiCharactersGetResponses200ContentApplicationJsonComputedModifiersOrigin;
                                originKey?: string;
                                originName?: string;
                            }[];
                            encumbrance?: number;
                            maxEncumbrance?: number;
                            drToDodge?: number;
                            drToMelee?: number;
                            drToRanged?: number;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        }[];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search items with fuzzy matching and locale awareness */
        get: {
            parameters: {
                query: {
                    q: string;
                    locale?: PathsApiEquipmentSearchGetParametersQueryLocale;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            itemType?: string;
                            id?: number;
                            key?: string;
                            name?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{itemType}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch full item by type and id */
        get: {
            parameters: {
                query?: {
                    key?: string;
                };
                header?: never;
                path: {
                    itemType: PathsApiEquipmentItemTypeIdGetParametersPathItemType;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsApiCharactersNewPostParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsApiCharactersNewPostResponses201ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersNewPostResponses201ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersNewPostResponses201ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsApiCharactersIdGetParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsApiCharactersIdGetResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersIdGetResponses200ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersIdGetResponses200ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsApiCharactersIdPatchParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsApiCharactersIdPatchRequestBodyApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersIdPatchResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersIdPatchResponses200ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsApiCharactersGetParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsApiCharactersGetResponses200ContentApplicationJsonModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersGetResponses200ContentApplicationJsonComputedModifiersStatistic {
    agility = "agility",
    strength = "strength",
    presence = "presence",
    toughness = "toughness"
}
export enum PathsApiCharactersGetResponses200ContentApplicationJsonComputedModifiersOrigin {
    armor = "armor",
    weapon = "weapon",
    pet = "pet",
    system = "system"
}
export enum PathsApiEquipmentSearchGetParametersQueryLocale {
    en = "en",
    pl = "pl"
}
export enum PathsApiEquipmentItemTypeIdGetParametersPathItemType {
    weapon = "weapon",
    armor = "armor",
    equipment = "equipment",
    pet = "pet"
}
export type operations = Record<string, never>;
