import { morkBorgColors } from "@/theme/morkBorgTheme";

export const gettingBetterStyles = {
  panel: {
    mb: 2.5,
    mt: 1,
    bgcolor: morkBorgColors.black,
    border: `3px solid ${morkBorgColors.black}`,
    boxShadow: `6px 6px 0 ${morkBorgColors.pink}`,
    color: morkBorgColors.white,
    p: { xs: 1.5, sm: 2.5 },
    pt: { xs: 3.25, sm: 3.75 },
    position: "relative",
  },
  title: {
    color: morkBorgColors.black,
    bgcolor: morkBorgColors.yellow,
    border: `3px solid ${morkBorgColors.black}`,
    boxShadow: `4px 4px 0 ${morkBorgColors.black}`,
    px: 1.25,
    py: 0.25,
    position: "absolute",
    top: { xs: -14, sm: -16 },
    left: { xs: 12, sm: 16 },
    transform: "rotate(-0.5deg)",
  },
  sectionGrid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "repeat(2, minmax(0, 1fr))" },
    gap: { xs: 1.5, sm: 2 },
  },
  section: {
    border: `2px solid ${morkBorgColors.grey}`,
    p: { xs: 1.25, sm: 1.5 },
    bgcolor: "#111111",
    minWidth: 0,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 1,
    mb: 1.25,
  },
  sectionTitle: {
    color: morkBorgColors.yellow,
    fontFamily: "'Antonio', sans-serif",
    fontSize: "0.75rem",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  factGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 1,
    alignItems: "center",
  },
  label: {
    color: morkBorgColors.yellow,
    opacity: 0.7,
    fontFamily: "'Antonio', sans-serif",
    fontSize: "0.64rem",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
  },
  value: {
    color: morkBorgColors.white,
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: "1.25rem",
    lineHeight: 1,
  },
  muted: {
    color: morkBorgColors.white,
    opacity: 0.72,
    fontSize: "0.86rem",
  },
  input: {
    width: 96,
    "& .MuiOutlinedInput-root": {
      bgcolor: morkBorgColors.yellow,
      borderRadius: 0,
      "& fieldset": { border: "none" },
    },
    "& input": {
      color: morkBorgColors.black,
      textAlign: "center",
      fontFamily: "'Bebas Neue', sans-serif",
      fontSize: "1.2rem",
      py: 0.75,
    },
  },
  wideInput: {
    "& .MuiOutlinedInput-root": {
      bgcolor: morkBorgColors.grey,
      borderRadius: 0,
      "& fieldset": { borderColor: morkBorgColors.darkGrey },
      "&:hover fieldset": { borderColor: morkBorgColors.yellow },
      "&.Mui-focused fieldset": { borderColor: morkBorgColors.yellow },
    },
    "& .MuiInputBase-input": {
      color: morkBorgColors.white,
    },
  },
  select: {
    minWidth: 160,
    color: morkBorgColors.white,
    bgcolor: morkBorgColors.grey,
    "& .MuiOutlinedInput-notchedOutline": {
      borderColor: morkBorgColors.darkGrey,
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      borderColor: morkBorgColors.yellow,
    },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      borderColor: morkBorgColors.yellow,
    },
  },
  actionRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
    justifyContent: "flex-end",
    mt: 2,
  },
  actionButton: {
    borderRadius: 0,
    border: `2px solid ${morkBorgColors.yellow}`,
    color: morkBorgColors.yellow,
    fontFamily: "'Antonio', sans-serif",
    fontSize: "0.66rem",
    letterSpacing: "0.14em",
    "&:hover": {
      bgcolor: morkBorgColors.yellow,
      color: morkBorgColors.black,
    },
  },
  applyButton: {
    borderRadius: 0,
    bgcolor: morkBorgColors.yellow,
    color: morkBorgColors.black,
    border: `2px solid ${morkBorgColors.yellow}`,
    fontFamily: "'Antonio', sans-serif",
    fontSize: "0.66rem",
    letterSpacing: "0.14em",
    "&:hover": {
      bgcolor: morkBorgColors.pink,
      borderColor: morkBorgColors.pink,
      color: morkBorgColors.black,
    },
  },
  warning: {
    mt: 1.5,
    p: 1.25,
    bgcolor: morkBorgColors.pink,
    color: morkBorgColors.black,
    border: `2px solid ${morkBorgColors.black}`,
    fontFamily: "'Antonio', sans-serif",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
} as const;
